# Generated by Django 6.0.7 on 2026-07-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('PRISE', 'Prise / Confirmée'), ('DISPONIBLE', 'Disponible'), ('EN_PAUSE', 'En Pause / Maintenance')], default='PRISE', max_length=15),
        ),
    ]
